### ISSUE TITLE
Wrong permissions on /usr/sbin/glexec

### ISSUE THREAD

**Issue by kreczko** [cernops/puppet-glexecwn#1]
As the title says, line
https://github.com/cernops/puppet-glexecwn/blob/master/manifests/install.pp#L20
should be
`mode => '611',` (-rw---x--x)
not
`mode => '6111',` (---s--s--x)
shouldn't it?

I am currently working on the module (see https://github.com/kreczko/puppet-glexecwn/tree/params_change) but I am not sure if it will make sense to make a pull request (many changes). I will try to summarise and group the commits before making the pull request, but it might take a while.

If you can wait, then this issue can be marked as 'fix in the pipeline'.

**Comment by schwicke** [comment]
Hi,
thanks for the feedback but I think the permission setting is actually 
correct.
The glexec executable must be suid root, see
https://wiki.nikhef.nl/grid/GLExec_Service_Reference_Card
else it goes to log-only mode.

**Comment by kreczko** [comment]
According to the link it should be
`-rws--x--x` for versions 0.7.X and up
or  `-r-sr-sr-x` for older version.

However, the current setting results in `---s--s--x` which is neither of the above (file not readable to root!)

So for glexec >- 0.7 the closest I found is '4611' (`-rwS--x--x` [note the capital S])

**Comment by schwicke** [comment]
Hi,

execution right is actually enough. We run it like that at CERN without 
problems on several thousand machines. These settings actually 
correspond to what yaim configures.
4711 is what they propose though.

**Comment by kreczko** [comment]
Since I am editing this bit anyway, shall I change it to 4711 in the module or rather make it configurable (as parameter) ?

**Comment by schwicke** [comment]
Maybe make it configurable but keep the most secure thing as default 
(which is what we have now).

**Comment by schwicke** [comment]
When you are done and have tested your changes please issue a pull 
request. We'll review this carefully and check if we can apply this.
As I said we are using this (and most of the other modules) now in 
production, and the glexec module runs already on all of our SLC6 batch 
resources as well as part of the SLC5 resources.  Thanks a lot for your 
feedback!
